services:
  logserverapp:
    build:
      context: ..
      dockerfile: LogServerApp/Dockerfile
    ports:
      - "5000:5000/udp"
    volumes:
      - logserverapp-logs:/app/logs

volumes:
  logserverapp-logs: